import { Router } from "express";
import { archiveCourse, createCourse, updateCourse } from "../controllers/courseController.js";
import { dashboard, listUsers, updateUserStatus, createTutor, listAllCourses, assignTutor, unassignTutor, listMessages, closeMessage } from "../controllers/adminController.js";
import { listPending, setEnrollmentStatus } from "../controllers/enrollmentController.js";
import { requireAuth } from "../middleware/requireAuth.js";
import { allowRoles } from "../middleware/allowRoles.js";
import { requirePasswordUpdated } from "../middleware/requirePasswordUpdated.js";
const router = Router();
router.use(requireAuth, allowRoles("ADMIN"), requirePasswordUpdated);
router.get("/dashboard", dashboard);
router.get("/users", listUsers);
router.patch("/users/:id/status", updateUserStatus);
router.post("/tutors", createTutor);
router.get("/courses", listAllCourses);
router.post("/courses", createCourse);
router.patch("/courses/:courseId", updateCourse);
router.delete("/courses/:courseId", archiveCourse);
router.post("/courses/:courseId/tutors/:tutorId", assignTutor);
router.delete("/courses/:courseId/tutors/:tutorId", unassignTutor);
router.get("/enrollments", listPending);
router.patch("/enrollments/:id", setEnrollmentStatus);
router.get("/messages", listMessages);
router.patch("/messages/:id/close", closeMessage);
export default router;
