import { Router } from "express";
import { changePassword, login, logout, me, register } from "../controllers/authController.js";
import { requireAuth } from "../middleware/requireAuth.js";
import { validate } from "../middleware/validate.js";
import { changePasswordSchema, loginSchema, registerSchema } from "../validators/authValidators.js";
const router = Router();
router.post("/register", validate(registerSchema), register);
router.post("/login", validate(loginSchema), login);
router.get("/me", requireAuth, me);
router.post("/logout", logout);
router.patch("/password", requireAuth, validate(changePasswordSchema), changePassword);
export default router;
