import "dotenv/config"; import express from "express"; import cors from "cors"; import helmet from "helmet"; import rateLimit from "express-rate-limit"; import { sessionMiddleware } from "./config/session.js"; import authRoutes from "./routes/authRoutes.js"; import courseRoutes from "./routes/courseRoutes.js"; import adminRoutes from "./routes/adminRoutes.js"; import tutorRoutes from "./routes/tutorRoutes.js"; import studentRoutes from "./routes/studentRoutes.js"; import contactRoutes from "./routes/contactRoutes.js"; import { errorHandler } from "./middleware/errorHandler.js";
const app = express();
app.set("trust proxy", 1);
app.use(helmet());
app.use(cors({ origin: process.env.CLIENT_URL, credentials: true }));
app.use(express.json({ limit: "1mb" }));
app.use(sessionMiddleware);
app.use("/api/auth/login", rateLimit({ windowMs: 15 * 60 * 1000, limit: 10, standardHeaders: true, legacyHeaders: false }));
app.get("/api/health", (req, res) => res.json({ status: "ok" }));
app.use("/api/auth", authRoutes);
app.use("/api/courses", courseRoutes);
app.use("/api/contact", contactRoutes);
app.use("/api/admin", adminRoutes);
app.use("/api/tutor", tutorRoutes);
app.use("/api/student", studentRoutes);
app.use((req, res) => res.status(404).json({ message: "Endpoint not found." }));
app.use(errorHandler);
export default app;
