import { Link } from "react-router-dom";
import { audiences, professionalCourses } from "../../data/siteContent";

export default function Home() {
  return <main>
    <section className="hero image-hero"><img className="hero-image" src="/images/icsf-kenyan-cybersecurity-classroom.webp" alt="Kenyan cybersecurity learners collaborating in a practical classroom" fetchPriority="high" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow">Professional cybersecurity training in Kenya</p><h1>Learn to protect, investigate and respond.</h1><p className="lead">ICSF delivers practical, instructor-led education in cybersecurity and digital forensics through online and physical classes.</p><div className="actions"><Link className="button" to="/courses">Explore our programs</Link><Link className="text-link" to="/admissions">How enrollment works →</Link></div></div></section>
    <section className="container intro"><p className="section-label">Why ICSF</p><h2>Training grounded in real digital environments.</h2><p>Our programs combine global standards with local relevance. Learners develop the judgement and practical confidence required to protect systems, handle digital evidence responsibly and respond to modern threats.</p><div className="feature-grid"><article><strong>Practical instruction</strong><p>Scenario-based learning focused on skills learners can apply.</p></article><article><strong>Flexible delivery</strong><p>Online and physical classes guided by expert instructors.</p></article><article><strong>Ethical practice</strong><p>Training rooted in integrity, privacy, law and human dignity.</p></article></div></section>
    <section className="home-programs"><div className="container"><div className="section-heading"><div><p className="eyebrow">Professional certificates</p><h2>Focused programs for modern digital challenges.</h2></div><Link className="inline-link" to="/courses">View all programs →</Link></div><div className="home-course-list">{professionalCourses.slice(0,4).map((course,index)=><Link to={`/courses/${course.id}`} key={course.id}><span>0{index+1}</span><strong>{course.title}</strong><small>View program →</small></Link>)}</div></div></section>
    <section className="container audience-section editorial-split"><div><p className="eyebrow">Who we serve</p><h2>Programs for learners and working professionals.</h2><div className="audience-grid">{audiences.map(item=><article key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></div><figure className="wide-photo portrait-photo"><img src="/images/icsf-network-security-class.webp" alt="Kenyan learners taking part in a network security practical" loading="lazy" /><figcaption>Hands-on learning designed around the systems professionals use.</figcaption></figure></section>
    <section className="home-cta"><div className="container"><div><p className="eyebrow">Admissions</p><h2>Take the next step with ICSF.</h2></div><div><p>Review the enrollment process or speak with the admissions team about current schedules, fees and program entry information.</p><div className="actions"><Link className="button" to="/admissions">View admissions</Link><Link className="text-link" to="/contact">Contact ICSF →</Link></div></div></div></section>
  </main>;
}
